### ISSUE TITLE
Error occurred while starting the project

### ISSUE THREAD

**Issue by n0hack** [preactjs/preact-www#1038]
Hello, I cloned the project to participate in translating docs into Korean. but when I start the project with a `npm run dev` command, I get the following errors. is there any solution?

## Error Messages

```
> dev
> concurrently "npm run dev:client" "npm run dev:lambda"

[1]
[1] > dev:lambda
[1] > netlify-lambda serve src/lambda
[1]
[0]
[0] > dev:client
[0] > preact watch
[0]
[1] netlify-lambda: Starting server
[1] node:internal/crypto/hash:68
[1]   this[kHandle] = new _Hash(algorithm, xofLen);
[1]                   ^
[1]
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:68:19)
[1]     at Object.createHash (node:crypto:138:10)
[1]     at module.exports (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/util/createHash.js:135:53)
[1]     at NormalModule._initBuildHash (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:417:16)
[1]     at handleParseError (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:471:10)
[1]     at /Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:503:5
[1]     at /Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:358:12
[1]     at /Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[1]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[1]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[1]     at /Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[1]     at context.callback (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[1]     at /Users/lucid/workspace/@docs/preact-www/node_modules/babel-loader/lib/index.js:59:71 {
[1]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[1]   library: 'digital envelope routines',
[1]   reason: 'unsupported',
[1]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[1] }
[1]
[1] Node.js v20.8.0
[1] npm run dev:lambda exited with code 1
[0]
<i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:8080/
[0] <i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.24:8080/
[0] <i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/Users/lucid/workspace/@docs/preact-www/src' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:68:19)
[0]     at Object.createHash (node:crypto:138:10)
[0]     at module.exports (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/util/createHash.js:135:53)
[0]     at NormalModule._initBuildHash (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:417:16)
[0]     at handleParseError (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:471:10)
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:503:5
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:358:12
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[0]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[0]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[0]     at runSyncOrAsync (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
[0]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[0]     at Array.<anonymous> (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[0]     at Storage.finished (/Users/lucid/workspace/@docs/preact-www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[0] ✖ ERROR Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:68:19)
[0]     at Object.createHash (node:crypto:138:10)
[0]     at module.exports (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/util/createHash.js:135:53)
[0]     at NormalModule._initBuildHash (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:417:16)
[0]     at handleParseError (/Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:471:10)
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:503:5
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/webpack/lib/NormalModule.js:358:12
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[0]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[0]     at iterateNormalLoaders (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[0]     at context.callback (/Users/lucid/workspace/@docs/preact-www/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[0]     at /Users/lucid/workspace/@docs/preact-www/node_modules/babel-loader/lib/index.js:59:71
```

**Comment by rschristian** [comment]
You'll need to make the following modification if you're running Node 18+:

> `package.json`

```diff
-"dev": "concurrently \"npm run dev:client\" \"npm run dev:lambda\"",
+ "dev": "cross-env NODE_OPTIONS=--openssl-legacy-provider concurrently \"npm run dev:client\" \"npm run dev:lambda\"",
```

**Comment by n0hack** [comment]
@rschristian It works ! thank you

**Comment by rschristian** [comment]
If you wanted to PR that I'd happily merge it, or I can do that myself later.
